### ISSUE TITLE
docs: 리드미 작성

### ISSUE THREAD

**Issue by haeseoklee** [Bithumb-Tech-Camp/Bithumb-Project#40]
![Simulator Screen Shot - iPhone 13 Pro - 2022-03-13 at 20 27 49](https://user-images.githubusercontent.com/20268101/158057285-079b6597-db96-453f-a4c2-0069a37f8a4a.png)
![Simulator Screen Shot - iPhone 13 Pro - 2022-03-13 at 20 28 18](https://user-images.githubusercontent.com/20268101/158057287-fbd24524-efc7-43f8-b453-e716e500373f.png)

**Comment by ParkHyeongSeok** [comment]
![Simulator Screen Shot - iPhone 12 - 2022-03-13 at 14 16 45](https://user-images.githubusercontent.com/77890228/158057214-54e33509-a420-4327-a169-65cbdeb2f400.png)
![Simulator Screen Shot - iPhone 12 - 2022-03-13 at 20 25 46](https://user-images.githubusercontent.com/77890228/158057218-f48a5e44-0ad2-4ec0-81ad-0df5fe37c06a.png)
![Simulator Screen Shot - iPhone 12 - 2022-03-13 at 20 25 57](https://user-images.githubusercontent.com/77890228/158057220-86be0caa-02f8-4e7c-90a7-d1b646fcf65f.png)
![Simulator Screen Shot - iPhone 12 - 2022-03-13 at 20 28 22](https://user-images.githubusercontent.com/77890228/158057300-5a0408f3-65a2-45d4-a7a1-356ad8ac9f24.png)
![Simulator Screen Shot - iPhone 12 - 2022-03-13 at 14 19 46](https://user-images.githubusercontent.com/77890228/158057224-171bf059-5bee-4e2f-b4bb-6c6e22b8dae3.png)
![Uploading Simulator Screen Shot - iPhone 12 - 2022-03-13 at 20.27.11.png…]()

**Comment by ParkHyeongSeok** [comment]
![Simulator Screen Shot - iPhone 12 - 2022-03-13 at 20 27 11](https://user-images.githubusercontent.com/77890228/158057409-acdd0c6e-4d98-4482-a7f6-2ade8fbd4521.png)

**Comment by db97828** [comment]
![Simulator Screen Shot - iPhone 13 Pro - 2022-03-13 at 20 36 41](https://user-images.githubusercontent.com/64210324/158057588-1385e205-0f52-438c-b73c-ac81218eb100.png)
![Simulator Screen Shot - iPhone 13 Pro - 2022-03-13 at 20 36 36](https://user-images.githubusercontent.com/64210324/158057590-de6d44c0-15fa-4dd5-8422-fac80bbf3683.png)
